###
### N e t z w e r k   -  V e r b i n d u n g   n o t w e n d i g
###

@host = localhost:3000/html
#@host = gener-iert-12345.herokuapp.com/api/fahrzeuge

### Homepage
https://{{host}}
Accept: text/html

### Suche
https://{{host}}/suche
Accept: text/html
