= Entwicklerhandbuch
Baran Özalp <oeba1011@hs-karlsruhe.de>
Valentin Gant <gava1012@hs-karlsruhe.de>
Vitali Reinhardt <revi1013@hs-karlsruhe.de>
Jannik Tschepke <tsja1011@hs-karlsruhe.de>

:doctype: book
:toc: left
:sectanchors:
:sectlinks:
:sectnums:
:source-highlighter: coderay
:icons: font

== Der Applikationsserver

=== Der Applikationsserver im Überblick

Unser Server implementiert eine Anwendungslogik, die get-, put-, post-requests etc. auf Fahrzeuge ermöglicht. Der AppServer wird mit GraphQL und Typescript umgesetzt, der Zugriff auf die Daten erfolgt über eine REST-Schnittstelle. Der Datenbankzugriff wird mit MongoDB ermöglicht.  Die Entities der Fahrzeuge sind jeweils eindeutig mit UUID's referenzierbar, die in unserer Anwendungslogik generiert werden.

.Use Cases
[plantuml,use-cases,svg]
----
include::use-cases.puml[]
----

Unter den Use-Cases befinden sich der Gast, der die Möglichkeit hat Fahrzeuge zu suchen und die dafür nötigen Dateien herunterzuladen ,der Admin kann zusätzlich Fahrzeuge anlegen, ändern, löschen und auch Dateien hochladen.

.Komponentendiagramm
[plantuml,komponenten,svg]
----
include::komponenten.puml[]
----

=== Die REST-Schnittstelle

Die REST-Schnittstelle ermöglicht die Benutzung aller 5 http-Methoden, zusätzlich ist die Option des Log-ins implementiert.

.Handler für die REST-Schnittstelle
[plantuml, FahrzeugHandler,svg]
----
include::FahrzeugHandler.puml[]
----

=== Der Anwendungskern

Der Anwendungskern beinhaltet unsere Router-Klasse, die Requests an die Handler-Klasse weiterleitet.
Der Client hat so die Möglichkeit über eine REST-Schnittstelle Requests abzusetzen.
Übergeben werden die Requests an die entsprechende Service-Klasse.
Ebenso ist der Zugriff auf den Mailserver und den Datenbankserver möglich.

.Anwendungskern mit Mongoose
[plantuml, FahrzeugService,svg]
----
include::FahrzeugService.puml[]
----

=== Interface für Entities und das Mongoose-Model

In Entity ist unser Model und Schema für Mongoose, in der alle properties des Fahrzeugs gelistet sind. Zusätzlich enthält es das Interface für unser Fahrzeug, die FahrzeugArt und die Hersteller.

.Entity, Model und Schema
[plantuml,Fahrzeug,svg]
----
include::Fahrzeug.puml[]
----

== Programmierrichtlinien für TypeScript und JavaScript

Für die Programmierung mit *TypeScript* und *JavaScript* wird folgende
Styleguides empfehlenswert:

[horizontal]
_Microsoft_:: https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines
_Angular_:: https://angular.io/docs/ts/latest/guide/style-guide.html
_React_:: https://github.com/airbnb/javascript/tree/master/react
