###
### N e t z w e r k   -  V e r b i n d u n g   n o t w e n d i g
###

@host = localhost:3000/api
#@host = brutale-blechbuechsen.herokuapp.com/api

### Suche alle Hersteller
https://{{host}}/hersteller
